# syntax=docker/dockerfile:1

FROM gustavofreze/php:8.5-builder-1.0.4 AS builder

COPY composer.json composer.lock ./

RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

COPY ./ ./

RUN composer dump-autoload --optimize --classmap-authoritative

FROM gustavofreze/php:8.5-runtime-1.0.4

LABEL org.opencontainers.image.title="gustavofreze/points-of-interest" \
      org.opencontainers.image.authors="Gustavo Freze"

COPY --from=builder --chown=www-data:www-data /var/www/html /var/www/html
