services:
  points-of-interest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: points-of-interest
    env_file:
      - ./config/local.env
    volumes:
      - ./src:/var/www/html/src
    depends_on:
      - points-of-interest-adm

  points-of-interest-adm:
    image: mysql:8.1
    restart: unless-stopped
    hostname: points-of-interest-adm
    container_name: points-of-interest-adm
    ports:
      - "3307:3306"
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "root"
    command: --default-authentication-plugin=caching_sha2_password --host-cache-size=0 --pid-file=/var/lib/mysql/mysqld.pid
    volumes:
      - ./config/database/mysql:/scripts/config

  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - points-of-interest
