# syntax=docker/dockerfile:1
FROM <base-images>/php:<runtime-minor>-development-1.0.0

LABEL org.opencontainers.image.title="<vendor>/<service-name>"
LABEL org.opencontainers.image.environment="development"

COPY --chown=www-data:www-data ./ /var/www/html
