name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  auto-review:
    name: Auto review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Run phpcs
        run: composer phpcs

      - name: Run phpmd
        run: composer phpmd

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Run unit tests
        env:
          XDEBUG_MODE: coverage
        run: composer test

      - name: Run mutation tests
        run: composer test-mutation
