name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  PHP_VERSION: '8.3'

jobs:
  auto-review:
    name: Auto review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Run review
        run: composer review

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Run tests
        run: composer tests
